### ISSUE TITLE
Webpack watch script throws error

### ISSUE THREAD

**Issue by gwbutler** [cabal-club/cabal-desktop#19]
I cloned this repository and installed its dependencies with `npm install`. When running `npm run watch`, webpack writes this error to the console:
```
ERROR in ./app/index.js
Module parse failed: Unexpected token (16:2)
You may need an appropriate loader to handle this file type.
|
| render(
|   <Provider store={store}>
|     <App />
|   </Provider>,
```
Changing the include path on line 19 of webpack.config.js to point at `${__dirname}` instead of `${__dirname}/app` fixes the issue, and I can start the app. I'm not that familiar with webpack, so I can't tell whether this is a proper fix or if I made an error earlier in the setup process.

**Comment by noffle** [comment]
Is this still happening?

**Comment by gwbutler** [comment]
I just repeated the process and got the same error, but now with an error log file from npm. 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cabal-desktop@1.0.0~prebuild: cabal-desktop@1.0.0
6 silly lifecycle cabal-desktop@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle cabal-desktop@1.0.0~build: cabal-desktop@1.0.0
8 verbose lifecycle cabal-desktop@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle cabal-desktop@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Grady\Downloads\cabal-desktop-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_101\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\youtube-dl\;C:\Program Files\ffmpeg\ffmpeg-20170804-44e9783-win64-static\bin\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\ngrok;C:\Program Files (x86)\Calibre2\;C:\WINDOWS\System32\OpenSSH\;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\Vim\vim81\;C:\Users\Grady\AppData\Local\Microsoft\WindowsApps;C:\Users\Grady\AppData\Local\atom\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\Grady\AppData\Roaming\npm;;C:\Users\Grady\AppData\Local\hyper\app-2.0.0\resources\bin
10 verbose lifecycle cabal-desktop@1.0.0~build: CWD: C:\Users\Grady\Downloads\cabal-desktop-master
11 silly lifecycle cabal-desktop@1.0.0~build: Args: [ '/d /s /c', 'webpack' ]
12 silly lifecycle cabal-desktop@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle cabal-desktop@1.0.0~build: Failed to exec build script
14 verbose stack Error: cabal-desktop@1.0.0 build: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid cabal-desktop@1.0.0
16 verbose cwd C:\Users\Grady\Downloads\cabal-desktop-master
17 error Windows_NT 10.0.17134
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.11.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error cabal-desktop@1.0.0 build: `webpack`
22 error Exit status 2
23 error Failed at the cabal-desktop@1.0.0 build script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the cabal-desktop package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs cabal-desktop
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls cabal-desktop
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gwbutler** [comment]
Just wanted to give an update and say this doesn't seem to be a problem anymore with the current code. (Win 10, node v.8.11.3, npm 5.6.0)
