### ISSUE TITLE
Cabal fails to start

### ISSUE THREAD

**Issue by okdistribute** [cabal-club/cabal-desktop#260]
Upon starting Cabal, nothing happens -- no windows open. I went to the commandline and started it in developer mode `npm start` to get the stack trace. Looks like there's a lock on the leveldb. 

Upon startup, if there is a lock on the leveldb, Cabal should close that lock gracefully and open a new instance, rather than failing silently.

Perhaps also ensuring that the leveldb will always be closed when exiting cabal would be ideal... but perhaps this is not always possible, for example, if the computer abruptly dies.

```
Error [OpenError]: IO error: lock /home/okdistribute/.cabal-desktop/v1/1eef9ad64e284691b7c6f6310e39204b5f92765e36102046caaa6a7ff8c02d74/views/LOCK: Resource temporarily unavailable
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/levelup/lib/levelup.js:119:23
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
Emitted 'error' event at:
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/levelup/lib/levelup.js:60:19
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/levelup/lib/levelup.js:119:14
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    [... lines matching original stack trace ...]
    at /home/okdistribute/node_modules/cabal-desktop/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
```

**Comment by cblgh** [comment]
thanks @okdistribute, we should def get the fix for the lockfile you propose
