### ISSUE TITLE
Trying to update the arch aur package for cabal-desktop

### ISSUE THREAD

**Issue by chovy** [cabal-club/cabal-desktop#299]
I get this error when running `makepkg -s`

`Error: Cannot find module 'sumchecker'`

**Comment by Powersource** [comment]
Had it fail for me with this now

```
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native/build'
  CC(target) Release/obj.target/sodium/binding.o
  SOLINK_MODULE(target) Release/obj.target/sodium.node
g++: error: /home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native/lib/libsodium-x64.so: No such file or directory
make: *** [sodium.target.mk:141: Release/obj.target/sodium.node] Error 1
make: Leaving directory '/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
gyp ERR! System Linux 5.10.9-arch1-1
gyp ERR! command "/usr/bin/node" "/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.13" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native
gyp ERR! node -v v15.7.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

Error: make: Entering directory '/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native/build'
  CC(target) Release/obj.target/sodium/binding.o
  SOLINK_MODULE(target) Release/obj.target/sodium.node
g++: error: /home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native/lib/libsodium-x64.so: No such file or directory
make: *** [sodium.target.mk:141: Release/obj.target/sodium.node] Error 1
make: Leaving directory '/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
gyp ERR! System Linux 5.10.9-arch1-1
gyp ERR! command "/usr/bin/node" "/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.13" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/sodium-native
gyp ERR! node -v v15.7.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/me/.cache/pacaur/cabal-desktop-git/src/cabal-desktop-git/node_modules/rxjs/internal/Subscriber.js:143:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! cabal-desktop@6.0.6 linux: `npm run build && electron-rebuild -f -w sodium-native && electron-builder --dir `
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the cabal-desktop@6.0.6 linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2021-01-29T12_32_01_031Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
:: Unable to build cabal-desktop-git - makepkg exited with code: 4
```
